name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: npm install

    - name: Build the package
      run: npm run build

    - name: Extract version from package.json
      id: get_version
      run: echo "::set-output name=version::$(node -p \"require('./package.json').version\")"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        release_name: Release v${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Build Files
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/dsfr-postale.umd.js
        asset_name: dsfr-postale.umd.js
        asset_content_type: application/javascript

    - name: Upload CSS
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/style.css
        asset_name: style.css
        asset_content_type: text/css
